#!/bin/bash
# Brand Login Testing Guide

# This script helps test the brand login feature

echo "=== BRAND LOGIN TESTING GUIDE ==="
echo ""
echo "1. SETUP: Create a test brand in MongoDB"
echo "   db.brands.insertOne({"
echo "     brandName: 'TestBrand',"
echo "     ownerEmail: 'testbrand@example.com',"
echo "     password: '<bcrypted_password>',"  
echo "     pickupLocation: 'Test Location',"
echo "     pincode: '123456',"
echo "     phone: '9876543210',"
echo "     address: 'Test Address',"
echo "     city: 'Test City',"
echo "     state: 'Test State',"
echo "     country: 'India',"
echo "     status: 'Active'"
echo "   })"
echo ""

echo "2. FRONTEND TESTING"
echo "   - Navigate to: http://localhost:3000/brand-login"
echo "   - Enter brand credentials:"
echo "     * Brand Name: TestBrand"
echo "     * Owner Email: testbrand@example.com"
echo "     * Password: (same password used to create brand)"
echo "   - Click 'Sign in'"
echo "   - Should redirect to: http://localhost:3000/brand/dashboard"
echo ""

echo "3. API TESTING (cURL)"
echo ""
echo "   Test endpoint:"
echo "   curl -X POST http://localhost:3000/api/admin/brand-login \\"
echo "     -H 'Content-Type: application/json' \\"
echo "     -d '{"
echo "       \"brandName\": \"TestBrand\","
echo "       \"ownerEmail\": \"testbrand@example.com\","
echo "       \"password\": \"testpassword\""
echo "     }'"
echo ""

echo "4. EXPECTED RESPONSES"
echo ""
echo "   Success (200):"
echo "   {"
echo "     \"success\": true,"
echo "     \"message\": \"Brand login successful\","
echo "     \"token\": \"eyJhbGc...\"," 
echo "     \"brand\": {"
echo "       \"id\": \"...\","
echo "       \"brandName\": \"TestBrand\","
echo "       \"ownerEmail\": \"testbrand@example.com\","
echo "       \"status\": \"Active\","
echo "       \"profileImage\": null"
echo "     }"
echo "   }"
echo ""

echo "5. ERROR CASES"
echo ""
echo "   Case 1: Missing fields (400)"
echo "   - Send request without brandName"
echo "   - Expected: 'Brand name, email, and password are required'"
echo ""
echo "   Case 2: Invalid credentials (401)"
echo "   - Use wrong password"
echo "   - Expected: 'Invalid brand name, email, or password'"
echo ""
echo "   Case 3: Brand not active (403)"
echo "   - Brand status is 'Pending' instead of 'Active'"
echo "   - Expected: 'Brand account is pending. Please contact support.'"
echo ""

echo "6. FRONTEND VERIFICATION"
echo ""
echo "   After successful login:"
echo "   - Check localStorage:"
echo "     * localStorage.token should have JWT"
echo "     * localStorage.brand_user should have brand data"
echo "   - Check redirect to /brand/dashboard"
echo "   - Verify dashboard shows brand info"
echo "   - Verify logout button works"
echo "   - Refresh page - should stay logged in"
echo ""

echo "7. IMPORTANT NOTES"
echo ""
echo "   - Brand status MUST be 'Active' for login"
echo "   - Password in database must be bcrypt hashed"
echo "   - Token expires in 30 days"
echo "   - Use BrandAuthService for all brand auth operations"
echo "   - Brand data stored separately from regular User model"
echo ""
